name: Deploy to Server
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}  # Add this line to specify the SSH port
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
        run: |
          echo "Starting deployment/..."
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
          scp -r -P $REMOTE_PORT .output/* $SERVER_USER@$SERVER_IP:$REMOTE_TARGET
          
          if [ $? -eq 0 ]; then
            echo "File transfer completed successfully."
          else
            echo "File transfer failed."
            exit 1
          fi
          
          echo "Deployment completed."